### PR TITLE
Sklearn cron

### PR DESCRIPTION
**Pull request by fschlimb**

### CODE REVIEW

**Comment by fschlimb** [comment]
@oleksandr-pavlyk @Alexander-Makaryev This is our new sklearn patches PR

**Comment by fschlimb** [comment]
@oleksandr-pavlyk @ogrisel Any idea how to stabilize the compatibility check (see .circleci/config.yml)?

Multiple issues remain:
- the numbers of passed/skpped etc differ between patched and non-patched sklearn. Not even the sums match. How can that be?
- how to deal with the 5 extra failures that @oleksandr-pavlyk expects?
- a proper check would compare test by test not only on summary stats. Probably ok for now.

patched:
```
11 failed, 10225 passed, 118 skipped, 1 xfailed, 13203 warnings in 376.78 seconds 
```
unpatched:
```
6 failed, 10058 passed, 112 skipped, 1 xfailed, 15394 warnings in 372.80 seconds 
```

**Comment by fschlimb** [comment]
@Alexander-Makaryev @oleksandr-pavlyk the estimator check fails on py2.7: https://travis-ci.com/IntelPython/daal4py/jobs/174360685 Please fix

**Comment by fschlimb** [comment]
the estimator check fails with python 2.7. @oleksandr-pavlyk @Alexander-Makaryev please fix.

**Comment by fschlimb** [comment]
@tomashek latest conda-build (3.17) makes building daal4py hang on OsX

**Comment by ogrisel** [comment]
>     the numbers of passed/skpped etc differ between patched and non-patched sklearn. Not even the sums match. How can that be?

It's hard to know. We would have see the "diff" of the tests that pass / fail / are skipped on each side.

>    a proper check would compare test by test not only on summary stats. Probably ok for now.

I think it would be usefull to do a proper diff to find the list of tests that yield different results on each side. A possible way to do it would be to output the report in some machine readable format and then write a script that collects the 2 lists of tests and their statuses.

One option would be to use the Junit XML export flag of pytest:

https://docs.pytest.org/en/latest/usage.html#creating-junitxml-format-files


>    how to deal with the 5 extra failures that @oleksandr-pavlyk expects?

I think we need to maintain a list of tests that are expected to fail in a text file and either:

- pass pytest command line argument to "deselect" the execution of those tests;
- execute them anyway but then ignore them when computing the diff suggested the above item.

To deselect blacklisted test it possible to generated a command line with a complex ["-k" expression](https://docs.pytest.org/en/latest/usage.html#specifying-tests-selecting-tests) with boolean operators:

```bash
python -m pytest --pyargs sklearn -k "not svm/tests/test_sparse.py::test_svc_iris and not ..."
```

**Comment by oleksandr-pavlyk** [comment]
> > ```
> > the numbers of passed/skpped etc differ between patched and non-patched sklearn. Not even the sums match. How can that be?
> > ```
> 
> It's hard to know. We would have see the "diff" of the tests that pass / fail / are skipped on each side.
> 

I have done some investigation here, and concluded that the discrepancy comes because in patched run, pytest ends up discovering both `daal4py.sklearn.monkeypatch.svm.SVC` and `sklearn.svm.classes.SVC`.

For example, in patched run I see

```text
 'tests/test_common.py::test_no_attributes_set_in_init[SVC-SVC0]',
 'tests/test_common.py::test_no_attributes_set_in_init[SVC-SVC1]',
```

while in unpatched run only

```
 'tests/test_common.py::test_no_attributes_set_in_init[SVC-SVC]',
```

@ogrisel Let us known if this could be mitigated somehow.

**Comment by oleksandr-pavlyk** [comment]
Am I using the `-k` correctly? Neither seems to work.

```
(def) [09:09:03 fxsatlin03 test_tmp]$ pytest -k "not sklearn.svm.tests.test_svm::test_sample_weights and not sklearn.svm.tests.test_svm::test_precomputed and not sklearn.svm.tests.test_sparse::test_sparse and not sklearn.svm.tests.test_sparse::test_svc_iris" --disable-warnings --pyargs sklearn.svm
========================================================= test session starts ==========================================================
platform linux -- Python 3.6.7, pytest-4.0.1, py-1.7.0, pluggy-0.8.0
rootdir: ~/work/saved_homedir/git/test_tmp, inifile:
collecting ...
====================================================== 1 warnings in 0.37 seconds ======================================================
ERROR: Wrong expression passed to '-k': not sklearn.svm.tests.test_svm::test_sample_weights and not sklearn.svm.tests.test_svm::test_precomputed and not sklearn.svm.tests.test_sparse::test_sparse and not sklearn.svm.tests.test_sparse::test_svc_iris
```


```
(def) [09:09:48 fxsatlin03 test_tmp]$ pytest -k "not sklearn/svm/tests/test_svm.py::test_sample_weights and not sklearn/svm/tests/test_svm.py::test_precomputed and not sklearn/svm/tests/test_sparse.py::test_sparse and not sklearn/svm/tests/test_sparse.py::test_svc_iris" --disable-warnings --pyargs sklearn.svm
========================================================= test session starts ==========================================================
platform linux -- Python 3.6.7, pytest-4.0.1, py-1.7.0, pluggy-0.8.0
rootdir: ~/work/saved_homedir/git/test_tmp, inifile:
collecting ...
====================================================== 1 warnings in 0.37 seconds ======================================================
ERROR: Wrong expression passed to '-k': not sklearn/svm/tests/test_svm.py::test_sample_weights and not sklearn/svm/tests/test_svm.py::test_precomputed and not sklearn/svm/tests/test_sparse.py::test_sparse and not sklearn/svm/tests/test_sparse.py::test_svc_iris
```

**Comment by oleksandr-pavlyk** [comment]
Am I using `-k` correctly? Running the following

```
python -m pytest -k "not sklearn/svm/tests/test_svm.py::test_sample_weights" -k "not sklearn/svm/tests/test_svm.py::test_precomputed" --disable-warnings --verbose --pyargs sklearn.svm.tests.test_svm
```

I still see both `test_precomputed` and `test_sample_weights` executed. See details section below.

<details>
(def) [09:19:29 fxsatlin03 test_tmp]$ python -m pytest -k "not sklearn/svm/tests/test_svm.py::test_sample_weights" -k "not sklearn/svm/tests/test_svm.py::test_precomputed" --disable-warnings --verbose --pyargs sklearn.svm.tests.test_svm
========================================================= test session starts ==========================================================
platform linux -- Python 3.6.7, pytest-4.0.1, py-1.7.0, pluggy-0.8.0 -- ~/work/miniconda3_cb3/envs/def/bin/python
cachedir: .pytest_cache
rootdir: ~work/saved_homedir/git/test_tmp, inifile:
collected 47 items

::test_libsvm_parameters PASSED                                                                                                  [  2%]
::test_libsvm_iris PASSED                                                                                                        [  4%]
::test_precomputed PASSED                                                                                                        [  6%]
::test_svr PASSED                                                                                                                [  8%]
::test_linearsvr PASSED                                                                                                          [ 10%]
::test_linearsvr_fit_sampleweight PASSED                                                                                         [ 12%]
::test_svr_errors PASSED                                                                                                         [ 14%]
::test_oneclass PASSED                                                                                                           [ 17%]
::test_oneclass_decision_function PASSED                                                                                         [ 19%]
::test_oneclass_score_samples PASSED                                                                                             [ 21%]
::test_tweak_params PASSED                                                                                                       [ 23%]
::test_probability PASSED                                                                                                        [ 25%]
::test_decision_function PASSED                                                                                                  [ 27%]
::test_decision_function_shape PASSED                                                                                            [ 29%]
::test_svr_predict PASSED                                                                                                        [ 31%]
::test_weight PASSED                                                                                                             [ 34%]
::test_sample_weights PASSED                                                                                                     [ 36%]
::test_auto_weight PASSED                                                                                                        [ 38%]
::test_bad_input PASSED                                                                                                          [ 40%]
::test_unicode_kernel PASSED                                                                                                     [ 42%]
::test_sparse_precomputed PASSED                                                                                                 [ 44%]
::test_linearsvc_parameters PASSED                                                                                               [ 46%]
::test_linearsvx_loss_penalty_deprecations PASSED                                                                                [ 48%]
::test_linear_svx_uppercase_loss_penality_raises_error PASSED                                                                    [ 51%]
::test_linearsvc PASSED                                                                                                          [ 53%]
::test_linearsvc_crammer_singer PASSED                                                                                           [ 55%]
::test_linearsvc_fit_sampleweight PASSED                                                                                         [ 57%]
::test_crammer_singer_binary PASSED                                                                                              [ 59%]
::test_linearsvc_iris PASSED                                                                                                     [ 61%]
::test_dense_liblinear_intercept_handling PASSED                                                                                 [ 63%]
::test_liblinear_set_coef PASSED                                                                                                 [ 65%]
::test_immutable_coef_property PASSED                                                                                            [ 68%]
::test_linearsvc_verbose PASSED                                                                                                  [ 70%]
::test_svc_clone_with_callable_kernel PASSED                                                                                     [ 72%]
::test_svc_bad_kernel PASSED                                                                                                     [ 74%]
::test_timeout PASSED                                                                                                            [ 76%]
::test_unfitted PASSED                                                                                                           [ 78%]
::test_consistent_proba PASSED                                                                                                   [ 80%]
::test_linear_svm_convergence_warnings PASSED                                                                                    [ 82%]
::test_svr_coef_sign PASSED                                                                                                      [ 85%]
::test_linear_svc_intercept_scaling PASSED                                                                                       [ 87%]
::test_lsvc_intercept_scaling_zero PASSED                                                                                        [ 89%]
::test_hasattr_predict_proba PASSED                                                                                              [ 91%]
::test_decision_function_shape_two_class PASSED                                                                                  [ 93%]
::test_ovr_decision_function PASSED                                                                                              [ 95%]
::test_gamma_auto PASSED                                                                                                         [ 97%]
::test_gamma_scale PASSED                                                                                                        [100%]

================================================ 47 passed, 12 warnings in 0.78 seconds ================================================
</details>

**Comment by ogrisel** [comment]
Indeed the -k flags is tricky to get right. Apparently there is a dedicated "--deselect" flag:

```bash
pytest -v --pyargs sklearn \
 --deselect "svm/tests/test_svm.py::test_sample_weights" \
 --deselect "sklearn/svm/tests/test_svm.py::test_precomputed" \
 --deselect "svm/tests/test_sparse.py::test_sparse" \
 --deselect "svm/tests/test_sparse.py::test_svc_iris" \
...
```

**Comment by ogrisel** [comment]
Use the "-v" flag to see the fully qualified names. Apparently those names change if you change the value of the `--pyargs` argument.

**Comment by ogrisel** [comment]
> @ogrisel Can deselection be used to skip over some parameters only ? Like not doing test_kmeans_fit_predict for float32?

I don't think so. But this is ok to skip a bit too much in that case.

**Comment by ogrisel** [comment]
I guess the most practical way to tackle the issue described in https://github.com/IntelPython/daal4py/pull/44#issuecomment-459750006 is to have specific logic when computing the diff of the two tests suites.

**Comment by fschlimb** [comment]
circleCi is green, but the log tells me it shouldn't because the summary lines report different numbers.

I suggest parsing the entire logfiles and printing a proper report.
- command line:
  - unpatched logfile
  - patched logfile
  - tests which should be ignored in comparison
- build maps for each logfile; test -> fails/success/skipped/...
- compare both maps
- tests in ignored (from command line) cannot invalidate the comparison
- print
  - tests which have been ignored
  - tests which differ
  - Something like 'Test results match'/'Test results differ'
- return 0 if all is fine,  !=0 if difference

**Comment by fschlimb** [comment]
@oleksandr-pavlyk I'd probably prefer a squash&merge

**Pull request merged**
