### PR TITLE
Resolve minor codefactor.io issues

### PR DESCRIPTION
**Pull request by cnguyen-uk**
# Description
This pull request resolves a few code quality issues found in codefactor.io, with the intention of making progress towards issue #316.

Changes proposed in this pull request:
- Use `enumerate()` instead of `range()` and `len()`
- Remove unnecessary "else" after "return"

### CODE REVIEW

**Comment by cnguyen-uk** [comment]
Those checks don't look too good - some pretty simple commits so now sure why there are so many check failures.

**Comment by napetrov** [comment]
@cnguyen-uk  - build failing across all platforms 

File "/usr/share/miniconda/envs/CB/conda-bld/daal4py_1602760673071/work/generator/gen_daal4py.py", line 554, in <genexpr>
    if not any(tmp_input_args[i].name.endswith(x) for x in ordered):
TypeError: list indices must be integers or slices, not tuple

**Comment by cnguyen-uk** [comment]
@napetrov Thanks for that, it was helpful. The fix that codefactor.io suggested wasn't a good one because the code following on wouldn't have been happy with it. To really fix the issue, we would need to use `enumerate()` instead of `range(len())`, as suggested by codefactor.io, but we would also need to rewrite the code after it. I'll leave that for now.

I've now submitted two new commits which undo the first set of changes in my PR's description. So really, this PR is just for one commit.

**Comment by cnguyen-uk** [comment]
@napetrov Hold off from approving this - will attempt a small change which may solve the two issues.

**Comment by cnguyen-uk** [comment]
@napetrov Changes made - good for a review once the tests (apart from Travis CI) pass.

**Comment by napetrov** [comment]
@cnguyen-uk  Thanks. actually Travis was fixed, so it should pass here as well

**Review by napetrov — APPROVED** [review]

**Pull request merged**
