### PR TITLE
Remove several unnecessary "else" after "return"

### PR DESCRIPTION
**Pull request by cnguyen-uk**
# Description
This pull request resolves most of the "Remove unnecessary "else" after "return"" code quality issues found in codefactor.io, with the intention of making progress towards issue #316.

Changes proposed in this pull request:
- Remove unnecessary "else" after "return"
- Final three commits remove errors in previous commits in this pull request

### CODE REVIEW

**Comment by napetrov** [comment]
@cnguyen-uk  Thanks a lot for your PR
with you changes set of new hits was introduced  - could you please also cover them as part of this PR?

**Comment by cnguyen-uk** [comment]
@napetrov Just to make sure that I understand correctly - you would like me to also resolve the 5 new issues uncovered by codefactor.io in this PR?

**Comment by napetrov** [comment]
@cnguyen-uk  - will be great if you can do 5, but particularly there are couple related to "else" after "return" that as i see appeared after initial refactoring of another "else" after "return" fix

**Comment by cnguyen-uk** [comment]
@napetrov Sure, no problem - I've submitted 4 more commits to resolve the 4 unnecessary "else" after "return" issues. The 5th commit was the resolve an issue with commit 82ca1b2, and the 6th commit resolves the remaining "unnecessary pass statement" issue.

**Review by napetrov — APPROVED** [review]

**Pull request merged**
