### PR TITLE
Introduce requerements file for documentation

### PR DESCRIPTION
**Pull request by napetrov**
# Description
Introduce initial version of requirements for doc build

### CODE REVIEW

**Comment by outoftardis** [comment]
I'm sure there is more than that even for the initial version of the file. docutils?

**Comment by napetrov** [comment]
Looks yes - https://dev.azure.com/azuredemoci/test/_build/results?buildId=40&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=12f1170f-54f2-53f3-20dd-22fc7dff55f9 

Looks those 2 packages bring relevant dependencies

**Comment by PetrovKP** [comment]
Need to delete https://github.com/IntelPython/daal4py/blob/master/azure-pipelines.yml ?

**Comment by napetrov** [comment]
> 
> 
> Need to delete https://github.com/IntelPython/daal4py/blob/master/azure-pipelines.yml ?

Not now.
1. commit new pipeline
2. Update config in azure
3. remove old pipeline

Or we will end up in commits without ci

**Comment by PetrovKP** [comment]
> Not now.
> 
> 1. commit new pipeline
> 2. Update config in azure
> 3. remove old pipeline
> 
> Or we will end up in commits without ci

I'm sure your changes won't break anything. I would do it here alone in one commit.

**Review by PetrovKP — APPROVED** [review]

**Pull request merged**
