### PR TITLE
Found and highlighted the case when NaNs were used in XGB training

### PR DESCRIPTION
**Pull request by RukhovichIV**

### CODE REVIEW

**Comment by RukhovichIV** [comment]
@SmirnovEgorRu , @PetrovKP, @ShvetsKS,
Please look at this PR. We should merge it as soon as possible (before 2020.3)
We discovered, that XGBoost is using NaNs for gbt training, but DAAL doesn't support it, so we will throw an exception every time we see a model, which was trained using NaNs

**Comment by PetrovKP** [comment]
Need to update examples then, because from public CI we have error:

> ERROR: test_gbt_cls_model_create_from_xgboost_batch (test_examples.TestExNpyArray)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/home/travis/miniconda/conda-bld/daal4py_1600696457816/test_tmp/tests/test_examples.py", line 81, in testit
>     result = self.call(ex)
>   File "/home/travis/miniconda/conda-bld/daal4py_1600696457816/test_tmp/tests/test_examples.py", line 221, in call
>     return ex.main(readcsv=np_read_csv)
>   File "/home/travis/miniconda/conda-bld/daal4py_1600696457816/test_tmp/examples/gbt_cls_model_create_from_xgboost_batch.py", line 65, in main
>     daal_model = d4p.get_gbt_model_from_xgboost(xgb_model)
>   File "build/daal4py_cy.pyx", line 20576, in _daal4py.get_gbt_model_from_xgboost
> TypeError: Missing values are not supported in daa4py Gradient Boosting Trees

**Comment by RukhovichIV** [comment]
> Need to update examples then, because from public CI we have error:
> 
> > ## ERROR: test_gbt_cls_model_create_from_xgboost_batch (test_examples.TestExNpyArray)
> > Traceback (most recent call last):
> > File "/home/travis/miniconda/conda-bld/daal4py_1600696457816/test_tmp/tests/test_examples.py", line 81, in testit
> > result = self.call(ex)
> > File "/home/travis/miniconda/conda-bld/daal4py_1600696457816/test_tmp/tests/test_examples.py", line 221, in call
> > return ex.main(readcsv=np_read_csv)
> > File "/home/travis/miniconda/conda-bld/daal4py_1600696457816/test_tmp/examples/gbt_cls_model_create_from_xgboost_batch.py", line 65, in main
> > daal_model = d4p.get_gbt_model_from_xgboost(xgb_model)
> > File "build/daal4py_cy.pyx", line 20576, in _daal4py.get_gbt_model_from_xgboost
> > TypeError: Missing values are not supported in daa4py Gradient Boosting Trees

As it turned out, XGBoost can also send all missing values to the left branch (we thought it would always be the right one). Seems like I fixed it now. There is no need in changing examples code

**Comment by PetrovKP** [comment]
we have a large log. can we not display service information in the example?

> test_gbt_cls_model_create_from_lightgbm_batch (test_examples.TestExPandasDF) ...   C_CONTIGUOUS : False
>   F_CONTIGUOUS : False
>   OWNDATA : False
>   WRITEABLE : True
>   ALIGNED : True
>   WRITEBACKIFCOPY : False
>   UPDATEIFCOPY : False
> [1]	training's multi_logloss: 1.1164
> [2]	training's multi_logloss: 0.887558
> [3]	training's multi_logloss: 0.710587
> [4]	training's multi_logloss: 0.598379
> [5]	training's multi_logloss: 0.514064
> [6]	training's multi_logloss: 0.457866
> [7]	training's multi_logloss: 0.404282
> [8]	training's multi_logloss: 0.364125
> [9]	training's multi_logloss: 0.32417
> [10]	training's multi_logloss: 0.294919
> [11]	training's multi_logloss: 0.26407
> [12]	training's multi_logloss: 0.242273
> [13]	training's multi_logloss: 0.215835
> [14]	training's multi_logloss: 0.196877
> [15]	training's multi_logloss: 0.18248
> [16]	training's multi_logloss: 0.169968
> [17]	training's multi_logloss: 0.154265
> [18]	training's multi_logloss: 0.143187
> [19]	training's multi_logloss: 0.133871
> [20]	training's multi_logloss: 0.125932
> [21]	training's multi_logloss: 0.117156
> [22]	training's multi_logloss: 0.111673
> [23]	training's multi_logloss: 0.104979
> [24]	training's multi_logloss: 0.0986897
> [25]	training's multi_logloss: 0.0941256
> [26]	training's multi_logloss: 0.0895267
> [27]	training's multi_logloss: 0.0854653
> [28]	training's multi_logloss: 0.0828074
> [29]	training's multi_logloss: 0.0792899
> [30]	training's multi_logloss: 0.0764583
> [31]	training's multi_logloss: 0.0732936
> [32]	training's multi_logloss: 0.0699909
> [33]	training's multi_logloss: 0.0674159
> [34]	training's multi_logloss: 0.0653253
> [35]	training's multi_logloss: 0.0634508
> [36]	training's multi_logloss: 0.0616914
> [37]	training's multi_logloss: 0.0592328
> [38]	training's multi_logloss: 0.0571625
> [39]	training's multi_logloss: 0.0559351
> [40]	training's multi_logloss: 0.0542363
> [41]	training's multi_logloss: 0.0533874
> [42]	training's multi_logloss: 0.0521564
> [43]	training's multi_logloss: 0.0511651
> [44]	training's multi_logloss: 0.0499394
> [45]	training's multi_logloss: 0.0489537
> [46]	training's multi_logloss: 0.0480024
> [47]	training's multi_logloss: 0.0470249
> [48]	training's multi_logloss: 0.0461712
> [49]	training's multi_logloss: 0.0452276
> [50]	training's multi_logloss: 0.0444481
> [51]	training's multi_logloss: 0.0437528
> [52]	training's multi_logloss: 0.0430757
> [53]	training's multi_logloss: 0.0424945
> [54]	training's multi_logloss: 0.0418157
> [55]	training's multi_logloss: 0.0412826
> [56]	training's multi_logloss: 0.0409475
> [57]	training's multi_logloss: 0.0404276
> [58]	training's multi_logloss: 0.0399762
> [59]	training's multi_logloss: 0.0395361
> [60]	training's multi_logloss: 0.0391643
> [61]	training's multi_logloss: 0.0386596
> [62]	training's multi_logloss: 0.0383265
> [63]	training's multi_logloss: 0.0378138
> [64]	training's multi_logloss: 0.0374893
> [65]	training's multi_logloss: 0.0370915
> [66]	training's multi_logloss: 0.0368145
> [67]	training's multi_logloss: 0.0364301
> [68]	training's multi_logloss: 0.0362284
> [69]	training's multi_logloss: 0.0359608
> [70]	training's multi_logloss: 0.0356214
> [71]	training's multi_logloss: 0.0354164
> [72]	training's multi_logloss: 0.0352028
> [73]	training's multi_logloss: 0.0349285
> [74]	training's multi_logloss: 0.0345731
> [75]	training's multi_logloss: 0.0343532
> [76]	training's multi_logloss: 0.0340425
> [77]	training's multi_logloss: 0.0337409
> [78]	training's multi_logloss: 0.0335285
> [79]	training's multi_logloss: 0.0332344
> [80]	training's multi_logloss: 0.0329137
> [81]	training's multi_logloss: 0.0326951
> [82]	training's multi_logloss: 0.0324366
> [83]	training's multi_logloss: 0.0322036
> [84]	training's multi_logloss: 0.0320647
> [85]	training's multi_logloss: 0.0318694
> [86]	training's multi_logloss: 0.031794
> [87]	training's multi_logloss: 0.0316469
> [88]	training's multi_logloss: 0.03144
> [89]	training's multi_logloss: 0.0312688
> [90]	training's multi_logloss: 0.0311169
> [91]	training's multi_logloss: 0.0309373
> [92]	training's multi_logloss: 0.0308505
> [93]	training's multi_logloss: 0.0306273
> [94]	training's multi_logloss: 0.0304427
> [95]	training's multi_logloss: 0.0303402
> [96]	training's multi_logloss: 0.0301917
> [97]	training's multi_logloss: 0.0300671
> [98]	training's multi_logloss: 0.0299055
> [99]	training's multi_logloss: 0.029708
> [100]	training's multi_logloss: 0.0295631
> [1]	training's multi_logloss: 1.1164
> [2]	training's multi_logloss: 0.887558
> [3]	training's multi_logloss: 0.710587
> [4]	training's multi_logloss: 0.598379
> [5]	training's multi_logloss: 0.514064
> [6]	training's multi_logloss: 0.457866
> [7]	training's multi_logloss: 0.404282
> [8]	training's multi_logloss: 0.364125
> [9]	training's multi_logloss: 0.32417
> [10]	training's multi_logloss: 0.294919
> [11]	training's multi_logloss: 0.26407
> [12]	training's multi_logloss: 0.242273
> [13]	training's multi_logloss: 0.215835
> [14]	training's multi_logloss: 0.196877
> [15]	training's multi_logloss: 0.18248
> [16]	training's multi_logloss: 0.169968
> [17]	training's multi_logloss: 0.154265
> [18]	training's multi_logloss: 0.143187
> [19]	training's multi_logloss: 0.133871
> [20]	training's multi_logloss: 0.125932
> [21]	training's multi_logloss: 0.117156
> [22]	training's multi_logloss: 0.111673
> [23]	training's multi_logloss: 0.104979
> [24]	training's multi_logloss: 0.0986897
> [25]	training's multi_logloss: 0.0941256
> [26]	training's multi_logloss: 0.0895267
> [27]	training's multi_logloss: 0.0854653
> [28]	training's multi_logloss: 0.0828074
> [29]	training's multi_logloss: 0.0792899
> [30]	training's multi_logloss: 0.0764583
> [31]	training's multi_logloss: 0.0732936
> [32]	training's multi_logloss: 0.0699909
> [33]	training's multi_logloss: 0.0674159
> [34]	training's multi_logloss: 0.0653253
> [35]	training's multi_logloss: 0.0634508
> [36]	training's multi_logloss: 0.0616914
> [37]	training's multi_logloss: 0.0592328
> [38]	training's multi_logloss: 0.0571625
> [39]	training's multi_logloss: 0.0559351
> [40]	training's multi_logloss: 0.0542363
> [41]	training's multi_logloss: 0.0533874
> [42]	training's multi_logloss: 0.0521564
> [43]	training's multi_logloss: 0.0511651
> [44]	training's multi_logloss: 0.0499394
> [45]	training's multi_logloss: 0.0489537
> [46]	training's multi_logloss: 0.0480024
> [47]	training's multi_logloss: 0.0470249
> [48]	training's multi_logloss: 0.0461712
> [49]	training's multi_logloss: 0.0452276
> [50]	training's multi_logloss: 0.0444481
> [51]	training's multi_logloss: 0.0437528
> [52]	training's multi_logloss: 0.0430757
> [53]	training's multi_logloss: 0.0424945
> [54]	training's multi_logloss: 0.0418157
> [55]	training's multi_logloss: 0.0412826
> [56]	training's multi_logloss: 0.0409475
> [57]	training's multi_logloss: 0.0404276
> [58]	training's multi_logloss: 0.0399762
> [59]	training's multi_logloss: 0.0395361
> [60]	training's multi_logloss: 0.0391643
> [61]	training's multi_logloss: 0.0386596
> [62]	training's multi_logloss: 0.0383265
> [63]	training's multi_logloss: 0.0378138
> [64]	training's multi_logloss: 0.0374893
> [65]	training's multi_logloss: 0.0370915
> [66]	training's multi_logloss: 0.0368145
> [67]	training's multi_logloss: 0.0364301
> [68]	training's multi_logloss: 0.0362284
> [69]	training's multi_logloss: 0.0359608
> [70]	training's multi_logloss: 0.0356214
> [71]	training's multi_logloss: 0.0354164
> [72]	training's multi_logloss: 0.0352028
> [73]	training's multi_logloss: 0.0349285
> [74]	training's multi_logloss: 0.0345731
> [75]	training's multi_logloss: 0.0343532
> [76]	training's multi_logloss: 0.0340425
> [77]	training's multi_logloss: 0.0337409
> [78]	training's multi_logloss: 0.0335285
> [79]	training's multi_logloss: 0.0332344
> [80]	training's multi_logloss: 0.0329137
> [81]	training's multi_logloss: 0.0326951
> [82]	training's multi_logloss: 0.0324366
> [83]	training's multi_logloss: 0.0322036
> [84]	training's multi_logloss: 0.0320647
> [85]	training's multi_logloss: 0.0318694
> [86]	training's multi_logloss: 0.031794
> [87]	training's multi_logloss: 0.0316469
> [88]	training's multi_logloss: 0.03144
> [89]	training's multi_logloss: 0.0312688
> [90]	training's multi_logloss: 0.0311169
> [91]	training's multi_logloss: 0.0309373
> [92]	training's multi_logloss: 0.0308505
> [93]	training's multi_logloss: 0.0306273
> [94]	training's multi_logloss: 0.0304427
> [95]	training's multi_logloss: 0.0303402
> [96]	training's multi_logloss: 0.0301917
> [97]	training's multi_logloss: 0.0300671
> [98]	training's multi_logloss: 0.0299055
> ok

**Comment by RukhovichIV** [comment]
@PetrovKP , until recently, I thought we can't. We already had `verbose: -1` parameter, which was expected to hide all debug information. I googled the problem, and it seems I found a solution.
We doesn't have any debug info (locally) now. Let's wait for CI

**Review by PetrovKP — APPROVED** [review]

**Pull request merged**
