### PR TITLE
Reduce tests for scikit-learn

### PR DESCRIPTION
**Pull request by PetrovKP**
Added to deselect tests that do not use any algorithms from daal4py patches

### CODE REVIEW

**Comment by PetrovKP** [comment]
azp skip

**Comment by PetrovKP** [comment]
@Mergifyio rebase

**Comment by SmirnovEgorRu** [comment]
It's ok to remove this in PCm or even CI, but need to keep full testing somewhere: CI/Nightly.

**Review by OnlyDeniko — APPROVED** [review]

**Comment by SmirnovEgorRu** [comment]
Please describe:
1) When reduced scope is used and when full scope?
2) What time do we save due to the changes in CI?

**Comment by PetrovKP** [comment]
> Please describe:
> 
> 1. When reduced scope is used and when full scope?
> 2. What time do we save due to the changes in CI?

1. Full scope use in private CI now - in future full scope will be only in private CI for Nightly and Weekly scope
2. 1.5 h -> 9m

This scope I want to add to conda-forge testing and to public CI for daal4py in oneDAL

**Review by SmirnovEgorRu — APPROVED** [review]

**Pull request merged**
