### PR TITLE
Remove boosting from req, revert unstable sklearn tests

### PR DESCRIPTION
**Pull request by PetrovKP**

### CODE REVIEW

**Comment by PetrovKP** [comment]
/intelci: run
set infra_branch=PetrovKP-patch-1

**Comment by PetrovKP** [comment]
/intelci: run
set infra_branch=PetrovKP-patch-1

**Comment by PetrovKP** [comment]
/intelci: run
set infra_branch=PetrovKP-patch-1

**Review by Pahandrovich — APPROVED** [review]

**Pull request merged**
