### PR TITLE
Reduce time for weights calculation

### PR DESCRIPTION
**Pull request by masdevas**
Drop extra work on weights calculation in cases when classes weights list contains ones.

### CODE REVIEW

**Comment by SmirnovEgorRu** [comment]
Overall - good. But, please, provide perf gains info and fix CI fails.

**Comment by PetrovKP** [comment]
Do other algorithms have such a problem? If not, maybe it is worth copying the solution from there or adding this part to the general one to support all algorithms?

**Review by Pahandrovich — APPROVED** [review]
LGTM

**Review by PetrovKP — APPROVED** [review]

**Pull request merged**
